### ISSUE TITLE
How does it compare to miso?

### ISSUE THREAD

**Issue by AleXoundOS** [ajnsit/concur#1]
These two projects have some similar background and goals. [**miso**](https://github.com/haskell-miso/miso) is inspired by Elm, Redux and Bobril.

"[Why concur](https://github.com/ajnsit/concur#why-concur)" section of README can be updated with such comparison.

**Comment by ajnsit** [comment]
I eventually need to update the rambling text in the README, but let me provide a small exposition here.

**Edit: this got longer than I expected. But there's still more stuff to say which I will find time to put in the README**

Miso faithfully follows the Elm architecture which means it has constraints similar to Elm. I wrote Concur to provide something more satisfying than Elm. By satisfying I mean that -

1. I don't want to feel artificially constrained. I can use my FP bag of tricks in predictable ways, and that is the standard way of doing things, so I'm never going against the grain. *It's a library in spirit, rather than a framework*.
2. Code complexity scales linearly with program complexity. Simple things are easy. Complex things are difficult but possible. With Elm, things are unpredictable. Simple things are OK to write, complex things range from OK to occasionally insanely complex.
3. Widget composition and refactoring is easy.

Here are some longer arguments with examples -

## Why Concur (vs. Elm/Miso)

### 1. Simpler and more powerful views

Elm inexorably mixes state, events, and views, and it then needs to enforce a rigid architecture to keep things sane. Concur provides the same view facilities as Elm, but keeps events independent.

A View in Elm
```elm
view : Model -> Html Msg
```

Here `Model` is the state, `Html` is the view, and `Msg` is events. There is no way to write views independent of these three things. It also feels semantically empty - this is the signature for all views, and there is little to be gained from changing any of these parameters in a single Elm program.

The `Msg` parameter feels especially magical in Elm. When I first saw the effect system it seemed magical. How is the view producing Msgs, and where do they go? How do I perform my own processing on Msgs? It all seems magically and inflexibly wired up.

A View in Concur
```haskell
view :: Widget HTML ()
```

Here `Widget` represents a view. There is no reference to either state or events. `HTML` is the type of view produced which can be easily changed, *and it's meaningful to do so* in a single program. For example, you can have a view that produces a message string, and then combine that with the rest of the program by providing a `Text -> HTML` function, and then mapping it over the view using `mapView`.

### 2. Minimum global state

Views (called Widgets) are all there are in Concur. And they are extremely modular and composable. There is no global state. There is no global Model, no global enumeration of Events , no global update function. But if a view needs a state, it's easy to add one. Either pass state around, or use a State or Reader Monad. Or use whatever else mechanism you want. The other views don't even have to think about that state (not even to plumb things together). If a view needs an anumeration of possible events, just add one. You are not forced to handle that event type in any of the other views (though you can chose to do that).

This is deeper than just aesthetics. A lot of times, the state of a nested widget is ephemeral, and we don't care about it.

A typical example is a menu widget. Within a menu widget we keep track of the current menu which is currently open while the user selects an option. When we add a menu widget to a larger program however, we really don't care about our current position in the menu. Menu option selection happens for only a very small fraction of the time spent by the user in the app. Menu open state is *not at the same level* as the state of the rest of the application. We only care about the final option selected by the user and how it changes the rest of the application UI. In Elm, you would still need to add information about which menu is currently open, to the global application state. In Concur, you either localise the state to just the menu widget, or you get rid of it entirely by using the flow primitives provided by the monad instance (more in the sections below).


### 3. Multiple backends

The type of the view restricts the events that can be raised by that view. So a `Text` view cannot produce `HTML` events. *This also makes it possible to have views that target different backends*. The current backends 'React' and 'virtual-dom', have a similar API and both provide their own `HTML` types. Just by switching the import from `Concur.VDOM (HTML)` to `Concur.React (HTML)` your application will switch from one library to the other. Eventually I will also provide a native ui backend, which will define a different view type (not named `HTML`).

### 4. A formal notion of dynamism and lifecycle.

The primary reason why we use client web frameworks is to provide dynamic behaviour, but Elm does not capture the notion of dynamism very well. Everything is proxied and understood via changes to a mixed bag of state, and views are derived as sterile mappings from it. For example, to create a simple program that displays some text when a button is clicked, you would write something like this -

```elm
type alias Model =  { clicked : Bool  }
model : Model
model =  { clicked = False }
type Msg = Click
update : Msg -> Model -> Model
update msg model =
  case msg of
    Click -> { model | clicked = True }
view : Model -> Html Msg
view model =
  div []
    [ if model.clicked then div [] [ text "Hello!" ]
      else button [ onClick Click ] [ text "Show message" ] ]
```

Even in such a small program, it is difficult to trace how the view changes. Does the button get displayed first or the text? Now imagine trying to figure this out in a large program.

The same program would instead be written as -

```haskell
main = div_ [] $ do
    button_ [] $ text "Show message"
    div_ [] $ text "Hello!"
```

In Concur, the notion of dynamism is captured by making `Widget` a `Monad`.

This makes it clear that the button gets displayed, and then when it's done, the text gets displayed.

Remember the type of views in concur -

```haskell
view :: Widget HTML ()
```

Here the `()` type parameter is what gets returned when the view is *done*. All views have a *lifecycle*. But unlike the ad-hoc lifecycle in React or Miso, here the lifecycle is principled and reflected in the type of the view. A widget that stops running after a while but doesn't return anything useful (e.g. a button) has the type `()`. A widget that displays something and never stops (e.g. a label)? It has the type `forall a. a` (or maybe `Void`). Forever looping widgets will again usually have this type. The type itself shows clearly that nothing scheduled to be run after this widget will ever run.

```haskell
main = do
    forever $ do
        button_ [] $ text "Ping"
        button_ [] $ text "Pong"
    text "This text will never be shown"
```

All `text` widgets have the return type `forall a. a` and thus can be composed with any other widget. So `[button [] [...], text ".."]` is conceptually equivalent to just the button `button [] [...]`, but the view also shows the text alongside the button.

This notion of lifecycle also allows attaching destructors and cleaning up resources, which are needed in large real world programs. In frameworks like React it's exposed to the user with magic pre-wired methods like `componentWillUnmount` etc. In concur you are provided enough power to conveniently manage resources yourself.

```haskell
main = div_ [] $ do
    button_ [] $ text "Start polling for stats"
    stats <- startPollForStats
    div []
      [  displayStats stats
      ,  button [] $ text "Stop polling for stats"
      ]
    stopPollForStats stats
    div_ [] $ text "Stopped polling"
```

Thanks to the monadic instance, we know that `startPollForStats` only starts after the first button is pressed. When the polling has started, we display stats, and a new button to stop polling. When this button is pressed, `stopPollForStats` stops the polling and cleans up any resources.

### 5. Easy widget composition, in space *and* time

As you can see from the previous section, Concur widgets can be composed together in both space (display widgetA alongside widgetB, or display widgetA nested inside widgetB) *and* time (display widgetA after widgetB stops running). This is because concur is built on a core of concurrency (hence the name). It uses STM to arbitrarily compose widgets and synchronise events without deadlocks. The Concur API is designed to be extremely composable. The user never has to manually plumb events, state, and view updates together.

```haskell
-- A counter widget returns the final count
counter :: Widget HTML Int

-- Compose two counters in parallel
-- The value of the first one to finish is returned
twoCounters :: Widget HTML (Either Int Int)
twoCounter = div []
    [ Left <$> counter
    , Right <$> counter
    ]
```

See how we `fmap`ped over a widget to designate the first widget as `Left` and the second as `Right`. `Widget` is a `Functor` and an `Applicative` (as it has to be, to be a `Monad`). These instances, as well as being able to nest widgets, allow an extremely natural composition of Widgets.

Note that nesting widgets is a special case of a more general operator called `orr` in concur. This operator takes in a list of widgets and puts them together at the same time in the DOM. The return value is the value of the first widget to finish. dom creation functions which *don't* end in an underscore `_` take a list of widgets which it combines using `orr`. i.e.

```haskell
div [] [widgetA, widgetB, widgetC] ====> div_ [] $ orr [widgetA, widgetB, widgetC]
```

Widgets also provide an instance of `Alternative` which provides the `<|>` operator. This operator can be used to show two widgets at the same time on the page -

E.g. To show two counter widgets on the page at the same time -
```haskell
counter <|> counter
```

There is also a special widget called `never` that doesn't have a view and never finishes. It can be used as an identity for `<|>`.

Conceptually -

```haskell
orr = fold (<|>) never
```

The fact that Concur Widgets are Monads, also means that you can use any Monad Transformer to structure code logic. It's easy to port any Elm app to Concur by simply using a `StateT model` transformer over Widget. You can use `ReaderT env` to provide a common environment to all app Widgets. You can use `ResourceT` for resource management etc.


### 6 Easy IO and integration with other JS / native libs

`Widget's are also an instance of `MonadIO`, providing an extremely easy way to perform IO in them.

This also makes integration with other JS libs very easy (since you can perform arbitrary JS function calls in Haskell IO).

As an example, to show an alert when a button is pressed -

```haskell
main = do
    button [] $ text "Show alert"
    liftIO $ [js| alert("Hello Alert!") |]
```

Wish to show some text after 10 seconds?

```haskell
main = do
    liftIO $ threadDelay 10000
    text "10 seconds passed"
```

**Comment by saurabhnanda** [comment]
> When we add a menu widget to a larger program however, we really don't care about our current position in the menu

Just nit-picking here. After everything is done, good UI engineering is about nailing the every small user interaction. How does a popover/modal interact with the open/close state of the menu? I don't know the correct answer. I'm just saying that I'd like my library/framework to solve this for me.

> 5. Easy widget composition, in space and time

I believe this is the USP of Concur, and unfortunately, at least for me, the examples given are not compelling enough. What would really appeal to me is a *real life* example of some UI and how clunky it is to engineer it in Elm & Reflex and how Concur solves it.

**Comment by ajnsit** [comment]
> >  When we add a menu widget to a larger program however, we really don't care about our current position in the menu

> Just nit-picking here. After everything is done, good UI engineering is about nailing the every small user interaction. How does a popover/modal interact with the open/close state of the menu? I don't know the correct answer. I'm just saying that I'd like my library/framework to solve this for me.

That's a good use case, thanks for the suggestion! I will add a popup + menu example to Concur next. If it turns out to be cumbersome (which I don't think it would) I'll refine the API.

> >  Easy widget composition, in space and time

> I believe this is the USP of Concur, and unfortunately, at least for me, the examples given are not compelling enough. What would really appeal to me is a real life example of some UI and how clunky it is to engineer it in Elm & Reflex and how Concur solves it.

I'm open to suggestions on UI examples to add to Concur . If you have any particular GUI spec that was cumbersome in some other framework then I'd give it a shot at implementing it in Concur. I did that once before with [Kirby Super Star Ultra Splits Timer GUI Challange](https://gist.github.com/lexi-lambda/701f1f1282401059f13a4220e8178ba4) - [Source](https://github.com/ajnsit/concur/blob/master/concur-vdom/examples/KirbySuperStarUltra.hs) - [Demo](https://ajnsit.github.io/concur/examples/kssu.jsexe/index.html)

**Comment by AleXoundOS** [comment]
nice!

**Comment by mpdairy** [comment]
Could you please discuss the speed of Concur vs Miso? The Concur examples all seem pretty snappy, except for the Mario one (https://ajnsit.github.io/concur/examples/mario.jsexe/index.html), which is noticeably choppier than Miso's mario example (https://mario.haskell-miso.org/). Is this inherent because Concur has to do more stuff behind the scenes to support the nice higher level Widget monad?

**Comment by ajnsit** [comment]
@mpdairy 

I imagine that there is an overhead to using Free monads and STM for monadic effects. This isn't significant for ordinary applications, where effects only happen on user input, but becomes significant when you have a tight loop performing animation every 50ms (as in the case of Mario). For ordinary applications, the performance should be pretty close to the performance of the raw backend (React or virtual-dom).

I have ideas on how to fix performance for animations, but frankly the performance for Mario was better than I expected, as I expected it to be completely unplayable, and I prioritized other things, such as the React backend, and API improvements, over it.

Performance improvements are pretty high on my list. I would appreciate people writing more apps with Concur and/or writing benchmarks, so I know where to focus my efforts.

**Comment by mpdairy** [comment]
Ok thanks. I'll try to make a little dashboard app for our database with Concur and see how well it does. @saurabhnanda do you think you'll add some Concur benchmarks to your excellent comparison page? (https://medium.com/@saurabhnanda/benchmarks-fp-languages-libraries-for-front-end-development-a11af0542f7e)

**Comment by ajnsit** [comment]
@mpdairy that would be awesome! Let me know how it goes!
