### ISSUE TITLE
Q: Signal or Pipe or something else?

### ISSUE THREAD

**Issue by zakaluka** [ajnsit/concur#14]
Hello,

_tl;dr_ When creating re-usable widgets with Concur Haskell, should I use Signals, Pipes, both, or something totally different (e.g. pulling the recursion into the parent widget)?

This is a question on the recommended way of developing reusable widgets with Concur.  As a caveat, I am a complete beginner in haskell (going through Learn You a Haskell right now).  I also do not intend to use Purescript at this time.

My journey started with reading the concur-documentation README, which was last updated with Signals information.  I did not see any mention of pipes in there, and read through the Signal code. 

When I went to look at examples, I saw that the [Concur Haskell example](https://github.com/concurhaskell/concur-react-examples/blob/master/src/PipeWidgets.hs) uses Pipes.  Following this, I found that Pipes were removed from the main Concur Haskell repo around the same time that Signals information was added to the documentation.  On the other hand, the [Concur Purescript examples](https://github.com/ajnsit/purescript-concur) use Signals.  In all fairness, the concur documentation does state that examples are being provided in Purescript.

Doing a quick search, I couldn't find code for either concept in the main Concur Haskell repo, though I did see pipes in the [concur-pipes](https://github.com/concurhaskell/concur-pipes) repo.  On the other hand, I did find `Signal` in `FRP.purs` in Concur Purescript.  Maybe these concepts already exist in Haskell?

I guess the point of all this is that I just am not sure how to proceed.  I also haven't been able to get [concur-react-starter](https://github.com/concurhaskell/concur-react-starter) running yet (various compilation issues on both Windows and Linux).  So I can't just copy paste the examples and try to run them either.  

I think this post has been rambly enough, so I'll stop.  Any pointers and guidance you can provide are greatly appreciated.

**Comment by ajnsit** [comment]
Hi, thanks for opening the issue!

As you point out, things are a bit muddled with the Concur-Haskell repo. Also I am yet to bring many of the changes I made to the Purescript version back into Haskell. Your post helps me prioritise the parts to focus on.

First, I would ignore the concur-pipes repo as that is incomplete and experimental, and should really be deleted (infact I just went ahead and did that).

I wrote Pipes and Signals to make it possible to compose looping widgets, however they are simple wrappers over the base concept of Concur which doesn't require either Pipes or Signals. Pipes were an earlier attempt and have not been very successful. I don't think I'll spend any time porting them to Haskell. Signals are newer, nicer, but still don't work as well as I would like them to be. A big problem with Concur Signals (and all other FRP based frameworks like Reflex) is that the order of widget composition matters. So if you want to display an error message on top of a form, you have to loop using some form of `mfix` to pass error messages "back up" from the form to the error div.

However, right now, pending some other big idea, Signals are the best we have. I'll go ahead and port signals to the Haskell version so you can use it if you really want to. However, I would also strongly suggest just using Concur as is. It's one less concept to learn, and I feel I should be able to come up with a better API soon.

**Comment by zakaluka** [comment]
Thank you for the quick response!  Hopefully I'll have the build working by the time you backport the Purescript changes and will be able to try some of this out.  If not, I'll probably have to open another issue and get some help.

**Comment by zakaluka** [comment]
> However, I would also strongly suggest just using Concur as is.

After a lot of thought and going back and forth mentally, I think I finally understand what you mean. 

Would the following architecture make sense for a Concur Haskell implementation?

1. Write reusable widgets as functions that do one thing well and return an appropriate value. 
1. Build up larger widgets from smaller ones.
1. Perform a recursive call only at the top-most level of the program.

In my mind, at least, this makes sense. The biggest challenge is making sure to identify what widgets need to speak to each other and use that knowledge to build the larger widgets.

**Comment by ajnsit** [comment]
Well not quite. In my opinion, it's perfectly fine to use recursion at any point, except in the narrow case where you end up writing a *never ending* widget (i.e. of the type `forall a. Widget HTML a`). So it's perfectly fine writing a widget that asks the user to input a number, and then asks if they want to input more numbers, and finally returns an array of numbers. This widget may loop an indeterminate number of times, but the end goal is to return a final value.

Basically treat widget organisation the same way as function organisation. The more granular they are, the easier it is to compose them. And if you write a function which loops forever processing input and changing the display (for example, an event loop) then that function best be at the top level.

And Concur actually goes one step further and gives you the ability to compose never ending widgets in meaningful ways, as long as you understand it will only be a Consumer, and not a Producer of meaningful data. (PS: There are ways to get data out of a never ending widget as well. See `remoteWidget` for an example).

Composing never ending widgets works because parent widgets completely control the child widgets, and can remove them from the view at will irrespective of whether the widget ended.

So you can imagine a "Dashboard" type widget which displays some complex data and even allows complex user interaction to slice and dice the data, however never supplies any data back to the rest of the app. It may have a type signature like -`dashboard :: CompanyData -> forall a. Widget HTML a`.

You can have a separate widget called `awaitDataChange` that watches for changes to the company data and returns the changed data. Perhaps it shows a UI that allows the user to edit the data themselves, or gets it from a database hook or some other source. You can still compose that with the dashboard widget like so -

```haskell
app data = do
  -- The dashboard widget will be removed as soon as new data comes in
  newData <- dashboard data <|> awaitDataChange
  -- Now we can just restart the dashboard widget with the new data
  app newData
```

The problem with Elm's model is all the plumbing, AND the fact that all the widgets are forced to update/recurse in lock step at the top level. Concur has no such restriction.

**Comment by zakaluka** [comment]
Thank you for the detailed reply.  I think I understand what you are saying, so my top priority now is to get Concur running locally as soon as possible so I can produce _something_ that can be reviewed.  

I think your example follows the mental picture I had - I was thinking that Consumers can accept incoming values (just like `dashboard` is taking in `data` as a parameter) but just won't return anything other than the visual display.  However, I hadn't connected the dots that widget composition could be used to force re-evaluation in such widgets.  Your example makes complete sense to me, as it doesn't always make sense for the `dashboard` widget to return a value.  

For the application I am thinking of, I can already envision visual pieces that are truly standalone and don't _need_ to return anything.

**Comment by zakaluka** [comment]
I am facing an issue on the last step in the instructions `stack build --stack-yaml stack-ghcjs.yaml`.

I am able to get GHCJS booted successfully.  After that, I see the following output:

```shell
GHCJS booted.
Building a GHCJS project. Note that GHCJS support in Stack is EXPERIMENTAL

Warning: Directory listed in myproject.cabal file does not exist: src-ghcjs
profunctors-5.2: configure
profunctors-5.2: build
Progress 0/5
```

It basically stays stuck on this step forever.

**Comment by ajnsit** [comment]
Glad you could get the build to work! You can ignore the warning in the console, that happens when your application is blocked for some event to happen but has no event handlers left. GHC detects that case and essentially stops listening, while also emitting the warning.

I could suppress that warning easily, by creating busywork for the application, but it's harmless so I let it be.

**Comment by ajnsit** [comment]
Closing this issue. @zakaluka please feel free to reopen, or create a new issue if/when you have more questions.

**Comment by zakaluka** [comment]
Thanks for all your help so far @ajnsit.  I'm hoping to spend some time this weekend working on a few proofs of concept.  Will keep you apprised of the progress.
